"""API map extracted from Whirlpool Android APK 6.8.3 strings.

This module intentionally keeps the map data-driven so the integration can expose newly
observed API surfaces through the `whirlpool_appliances.call_api` service without requiring a
new entity for every Whirlpool cloud feature.
"""
from __future__ import annotations

CLOUD_BASE_URLS = {
    "US_PROD": "https://api.whrcloud.com",
    "EU_PROD": "https://prod-api.whrcloud.eu",
    "EU_LEGACY": "https://api.whrcloud.eu",
    "US_STAGE": "https://stage-api.whrcloud.com",
    "EU_STAGE": "https://api-stg.whrcloud.eu",
    "US_QA": "https://qa-api.whrcloud.com",
    "US_DEV": "https://dev-api.whrcloud.com",
    "US_TEST": "https://api-test.whrcloud.com",
    "EU_TEST": "https://api-test.whrcloud.eu",
}

LOCAL_PROVISIONING_ENDPOINTS = [
    "http://192.168.10.1/connect.cgi",
    "http://192.168.10.1/submit_network",
]

OAUTH_ENDPOINTS = [
    "/oauth/custom/authorize",
    "/oauth/token",
    "/voice/oauth/authorize",
    "/api/v1/oauth/revoke-token",
]

DISCOVERED_API_PATHS = [
    "/api/v1/ac/getACFilterStatus/{said}",
    "/api/v1/ac/resetACFilter",
    "/api/v1/accessory",
    "/api/v1/accessory/cycle-history",
    "/api/v1/accessory/cycle-history/favorites",
    "/api/v1/accessory/cycle-history/favorites/delete/{favoriteId}",
    "/api/v1/accessory/cycle-history/favorites/notes/{favoriteId}",
    "/api/v1/accessory/cycle-history/favorites/{cycleId}",
    "/api/v1/accessory/cycle-history/lifecycle/",
    "/api/v1/accessory/cycle-history/{cycleId}",
    "/api/v1/accessory/expert/cycle/{cycleId}",
    "/api/v1/accessory/ota",
    "/api/v1/accessory/rangeextender/enable/{cycleId}",
    "/api/v1/accessory/{serialNumber}",
    "/api/v1/account/favorites/entity/cycle",
    "/api/v1/account/favorites/{said}",
    "/api/v1/account/favorites/{said}/entity/cycle/id/{id}",
    "/api/v1/account/privacy",
    "/api/v1/accounts",
    "/api/v1/accounts/update_password",
    "/api/v1/alexaappfallbackurls",
    "/api/v1/appliance/appliances/createReminder",
    "/api/v1/appliance/command",
    "/api/v1/appliance/status/{said}",
    "/api/v1/appliance/{applianceId}",
    "/api/v1/appliance/{said}/sync",
    "/api/v1/appliances/claim/",
    "/api/v1/appliances/unclaim/{said}",
    "/api/v1/appliancesForLoc/{locationId}",
    "/api/v1/channel/{said}",
    "/api/v1/client_auth/PrivacyContent/countryCd/{country}/languageCd/{lang}",
    "/api/v1/client_auth/TncContent/countryCd/{country}/languageCd/{lang}",
    "/api/v1/client_auth/account/validate",
    "/api/v1/client_auth/accounts",
    "/api/v1/client_auth/accounts/forgotPassword/{email}",
    "/api/v1/client_auth/accounts/resend_confirmation/{email}",
    "/api/v1/client_auth/client_version",
    "/api/v1/client_auth/countriesAndStates",
    "/api/v1/client_auth/debug/mobileActivityTraces",
    "/api/v1/client_auth/esp/getpolicydetails",
    "/api/v1/client_auth/getContentFile",
    "/api/v1/client_auth/location",
    "/api/v1/client_auth/privacy_policy",
    "/api/v1/client_auth/sso/login",
    "/api/v1/client_auth/sso/profiles",
    "/api/v1/client_auth/terms_agreement",
    "/api/v1/client_auth/webSocketUrl",
    "/api/v1/cognito/identityid",
    "/api/v1/contents/all/{ddmKey}",
    "/api/v1/esp/{said}",
    "/api/v1/getEnabledFromAlexaStatus/{accountID}",
    "/api/v1/getLocalizedDateAndTimeForSaids",
    "/api/v1/getUserDetails",
    "/api/v1/history/cycle",
    "/api/v1/history/faultCode",
    "/api/v1/live/collect/{said}",
    "/api/v1/localizedDateAndTimeForSaids",
    "/api/v1/location",
    "/api/v1/location/allLocations/account/{accountId}",
    "/api/v1/locations/location/{locationId}",
    "/api/v1/messages/{messageId}",
    "/api/v1/privacy_policy",
    "/api/v1/rms/{app}/views/{filterName}",
    "/api/v1/sso/profiles",
    "/api/v1/sso/profiles/{ssoAttachProfileId}",
    "/api/v1/ts/ota/descriptor",
    "/api/v1/ts/ota/descriptor/status/{said}",
    "/api/v1/ts/ota/status/{said}",
    "/api/v1/users/{userId}/messages",
    "/api/v1/users/{userId}/messages/{messageId}",
    "/api/v1/wwp/devicelink",
    "/api/v1/wwp/devicelinkstatus",
    "/api/v1/wwp/deviceunlink",
    "/api/v1/wwp/link",
    "/api/v2/DeviceDataModel",
    "/api/v2/account/favorites/{said}",
    "/api/v2/checkForFirmwareUpdate/{said}",
    "/api/v2/client_auth/whatsNew/{version}",
    "/api/v2/location/tsApplianceAtLoc",
    "/api/v2/location/{locationId}",
    "/api/v2/notifications/subscriptions/multi",
    "/api/v2/unRegisterDeviceIdForPush",
    "/api/v2/updateAppliances",
    "/api/v2/user/notification/device/{deviceId}",
    "/api/v3/account/favorites/{said}/{favoriteId}",
    "/api/v3/accounts/{accountId}",
    "/api/v3/appliance/all/account/{accountId}",
    "/api/v3/registerDeviceIDForPush",
    "/api/v4/client_auth/accounts",
    *OAUTH_ENDPOINTS,
]

APPLIANCE_FUNCTIONS = {
    "get_status": {"method": "GET", "path": "/api/v1/appliance/status/{said}"},
    "sync": {"method": "GET", "path": "/api/v1/appliance/{said}/sync"},
    "send_command": {"method": "POST", "path": "/api/v1/appliance/command"},
    "create_reminder": {"method": "POST", "path": "/api/v1/appliance/appliances/createReminder"},
    "get_channel": {"method": "GET", "path": "/api/v1/channel/{said}"},
    "get_favorites": {"method": "GET", "path": "/api/v1/account/favorites/{said}"},
    "get_favorites_v2": {"method": "GET", "path": "/api/v2/account/favorites/{said}"},
    "delete_favorite": {"method": "DELETE", "path": "/api/v3/account/favorites/{said}/{favoriteId}"},
    "get_ac_filter_status": {"method": "GET", "path": "/api/v1/ac/getACFilterStatus/{said}"},
    "reset_ac_filter": {"method": "POST", "path": "/api/v1/ac/resetACFilter"},
    "check_firmware": {"method": "GET", "path": "/api/v2/checkForFirmwareUpdate/{said}"},
    "ota_descriptor_status": {"method": "GET", "path": "/api/v1/ts/ota/descriptor/status/{said}"},
    "ota_status": {"method": "GET", "path": "/api/v1/ts/ota/status/{said}"},
    "esp": {"method": "GET", "path": "/api/v1/esp/{said}"},
    "live_collect": {"method": "GET", "path": "/api/v1/live/collect/{said}"},
}

IOT_CLIENT_METHODS = [
    "connectToAppliance",
    "connectToAppliances",
    "publishCommand",
    "publishComplementaryCommand",
    "publishDishCommand",
    "publishGetStatus",
    "publishLaundryCommand",
    "publishMatterRequest",
    "setCavityLight",
    "signOut",
]
